# Site settings 配置站点
title: '陈浩杰的个人博客'
description: '时而孤独，时而放纵，热爱生活。喜爱技术，情感丰富，爱听故事，只是没酒。'
keyword: '陈浩杰, 陈浩杰的博客,河南大学学生, 河大学生,河大'
url: 'https://haojiechen.github.io/' # your host
baseurl: 'https://haojiechen.github.io/'

# Navigation links
nav:
  home: '/'
  tags: '/tags.html'


# Footer
footer:
  since: 2017
# Author 配置博主信息
author: '陈浩杰'
nickname: '怪人'
bio: '河南大学本科在读，热爱技术，不断发现和体验生活'
avatar: 'assets/img/profile.jpg'

# Search
search: true

# Night mode
nightMode: true

# Comments
disqus: false
disqus_url: ""
livere: false
livere_uid：

# Reward 赞赏功能 by Ray-Eldath
reward:
  enable: true
  reward_comment: '真诚赞赏 手有余香'
  wechatpay: '/assets/img/wechat.jpg'
  alipay: '/assets/img/alipay.jpg'

# b2t 回到顶部 by Ray-Eldath
b2t: true

# Share
social-share: true
social-share-items: [ 'weibo' , 'wechat','qq', 'twitter']

# theme color 主题皮肤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'seaOfClouds'

# SNS settings 配置社交网站url: weibo, zhihu, twitter, instagrame, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  weibo: '//weibo.com'
  github: '//github.com/haojiechen'
  zhihu: 'https://www.zhihu.com/people/chen-hao-jie-22-21/activities'

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

RSS: false
permalink: /:year/:month/:day/:title.html
# Plugins
plugins: [jekyll-paginate]
